apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-agent-api
  namespace: fsi
  labels:
    app: pdf-agent-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-agent-api
  template:
    metadata:
      labels:
        app: pdf-agent-api
    spec:
      containers:
      - name: pdf-agent-api
        image: pdf-agent-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: pdf-agent-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: pdf-agent-config
              key: PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: pdf-agent-config
              key: ENVIRONMENT
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: pdf-agent-config
              key: DEBUG
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: pdf-agent-config
              key: LOG_LEVEL
        - name: API_BASE
          valueFrom:
            secretKeyRef:
              name: pdf-agent-secret
              key: API_BASE
        - name: MODEL_ID
          valueFrom:
            secretKeyRef:
              name: pdf-agent-secret
              key: MODEL_ID
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: pdf-agent-secret
              key: API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always 